name: Eval Blocks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  # Mainnet

  blocks-cloudflare-mainnet:
    name: blocks (https://cloudflare-eth.com)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://cloudflare-eth.com
  blocks-1rpc-mainnet:
    name: blocks (https://1rpc.io/eth)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://1rpc.io/eth
  blocks-ankr-mainnet:
    name: blocks (https://rpc.ankr.com/eth)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://rpc.ankr.com/eth
  blocks-llamarpc-mainnet:
    name: blocks (https://eth.llamarpc.com)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth.llamarpc.com
  blocks-omniatech-mainnet:
    name: blocks (https://endpoints.omniatech.io/v1/eth/mainnet/public)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://endpoints.omniatech.io/v1/eth/mainnet/public
  blocks-publicnode-mainnet:
    name: blocks (https://ethereum-rpc.publicnode.com)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://ethereum-rpc.publicnode.com
  # eth_chainId returns undefined
  blocks-payload-mainnet:
    if: false
    name: blocks (https://rpc.payload.de)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://rpc.payload.de
  blocks-blastapi-mainnet:
    name: blocks (https://eth-mainnet.public.blastapi.io)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth-mainnet.public.blastapi.io
  blocks-meowrpc-mainnet:
    name: blocks (https://eth.meowrpc.com)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth.meowrpc.com
  blocks-drpc-mainnet:
    name: blocks (https://eth.drpc.org)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth.drpc.org
  blocks-merkle-mainnet:
    name: blocks (https://eth.merkle.io)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth.merkle.io
  blocks-nodeconnect-mainnet:
    name: blocks (https://eth.nodeconnect.org)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://eth.nodeconnect.org

  # Polygon

  blocks-polygon:
    name: blocks (https://polygon-rpc.com)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://polygon-rpc.com

  blocks-quicknode-polygon:
    name: blocks (https://rpc-mainnet.matic.quiknode.pro)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://rpc-mainnet.matic.quiknode.pro

  blocks-nodies-polygon:
    name: blocks (https://polygon-pokt.nodies.app)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://polygon-pokt.nodies.app

  blocks-onfinality-polygon:
    name: blocks (https://polygon.api.onfinality.io/public)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://polygon.api.onfinality.io/public

  # Celo

  blocks-celo:
    name: blocks (https://forno.celo.org)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://forno.celo.org

  # Blast

  blocks-blast:
    name: blocks (https://rpc.blast.io)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://rpc.blast.io

  # Optimism

  blocks-optimism:
    name: blocks (https://mainnet.optimism.io)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://mainnet.optimism.io

  # Arbitrum

  blocks-arbitrum:
    name: blocks (https://arb1.arbitrum.io/rpc)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://arb1.arbitrum.io/rpc

  # Base

  blocks-base:
    name: blocks (https://mainnet.base.org)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run blocks.ts https://mainnet.base.org
